#!/usr/bin/env python
import sys
import os
from sstools.commands.filter_bam import FilterBam
from sstools.commands.mark_haplotype import MarkHaplotype
from sstools.commands.mark_duplicate import MarkDuplicate
from sstools.commands.mark_region import MarkRegion
from sstools.commands.stat_genomic_coverage import StatGenomicCoverage
from sstools.commands.stat_duplicate import StatDuplicate
from sstools.commands.calculate_cwr import CalculateCWR
from sstools.commands.stat_bin_read import StatBinRead

usage = """
Tools for Strand-seq analysis.

Usage: %s <command> [options]

Commands:
    -- Developed
       FilterBam        Filter bam file for Strand-seq.
       MarkDuplicate    Mark duplicates for Strand-seq.
       MarkRegion       Mark regions, such as whitelist or blacklist.
       MarkHaplotype    Mark the parental for each read according to provided HET SNVs.
       StatGenomicCov   Statistic genomic coverage.
       StatDuplicate    Statistic PCR duplicate.
       CalculateCWR     Calculate Crick/Watson ratio.
       StatBinRead      Statistic read count for each bin and plot barplot.

    -- Developing
       

    -- Assembly
       ClusterCells
       SplitHaplotype
       MakeBaseMatrix
       MergeBaseMatrix
       

""" % os.path.basename(__file__)

def main():
    if len(sys.argv) == 1:
        print("Error: please provide command.")
        print(usage)
        exit(1)
        
    command = sys.argv[1]
    if command == "FilterBam":
        FilterBam()
    elif command == "MarkHaplotype":
        MarkHaplotype()
    elif command == "MarkDuplicate":
        MarkDuplicate()
    elif command == "MarkRegion":
        MarkRegion()
    elif command == "StatGenomicCoverage":
        StatGenomicCoverage()
    elif command == "StatDuplicate":
        StatDuplicate()
    elif command == "CalculateCWR":
        CalculateCWR()
    elif command == "StatBinRead":
        StatBinRead()
    else:
        print("Error: unknown command %s." % command)
        print(usage)
        exit(1)


if __name__ == '__main__':
    main()
    
